### ISSUE TITLE
Export to OPML fails on Nexus 7 2013

### ISSUE THREAD

**Issue by alexandrul** [Etuldan/spaRSS#163]
No writable SD card mounted

**Comment by Etuldan** [comment]
spaRSS use this API for the output directory : https://developer.android.com/reference/android/os/Environment.html#getExternalStorageDirectory%28%29

Could you check this when you try to export as OPML : 
This directory may not currently be accessible if it has been mounted by the user on their computer, has been removed from the device, or some other problem has happened


I'll anyway change this directory to the download one (in order to let the root of sdcard/internal storage clean)

**Comment by ildar** [comment]
I disagree. The app lacks permission to write since Android 6.
https://github.com/TeamAmaze/AmazeFileManager/issues/470
https://github.com/jensstein/oandbackup/issues/125
I suggest the very quick fix changing folder to
/sdcard/Android/data/$APPID/... that doesn't require playing with
permissions.
