### ISSUE TITLE
Enhancement: group rss

### ISSUE THREAD

**Issue by homersimpsons** [Etuldan/spaRSS#164]
Can you please add an 'arrow' to group all subrss of a group. For example I create :
NEWS (group)
|google
|the verge
|the guardian

I click on the arrow and then I have:
NEWS

With nothing under

**Comment by gitumor** [comment]
you can move feeds into a group by grabbing the handle and dropping it onto the group, then choose to move it into the group rather than above or below.

but grouping could be improved. user should be able to initially add a feed into a group, rather than having to add a feed first and only then be able to move it into a group.

**Comment by IzzySoft** [comment]
@homersimpsons are you asking for something like #168 ? If so, you might wish to add your "thumbs-up emoji" to the initial post there :)

**Comment by homersimpsons** [comment]
@IzzySoft Yes in fact :)

**Comment by IzzySoft** [comment]
I've lost hope on that. 1.5 years, and the issue is still open and unprocessed. No commits for the last 4 months – and looking at the [code frequency](/Etuldan/spaRSS/graphs/code-frequency) isn't encouraging either. With @Etuldan being last active in 2/2017, this isn't really much active. Not blaming anyone, mind me (it's everyone's free time spent on this) – just stating the facts.
