### ISSUE TITLE
feed43 feeds show error every now and then

### ISSUE THREAD

**Issue by arunvikraman** [Etuldan/spaRSS#35]
Now a days i get this "ERROR: Timed out waiting for data to be extracted. If the problem persists, try simplifying your search patterns." 

When I check the feed in the browser there's no problem; all feeds show fine and theres no error feeds. It happens only in phones which are connected to internet through the day. Theres no ERROR feeds in phones that fetches once in a while, say twice a day.

feed43 feed proxied through feedburner:
http://feeds.feedburner.com/etbsnl
http://feeds.feedburner.com/toibsnl

**Comment by arunvikraman** [comment]
Feedburner pingshots handle it most of the times. But still I have some Timed out ERRORs popping up now and then.

**Comment by Etuldan** [comment]
I just check on or you feed, and this one : http://feeds.feedburner.com/etbsnl just 'crash' on my computer browser : 

There has been an error of some kind. Ack!
FeedBurner could not deliver this feed to you because of the specific problem listed below:
Feed Address: http://feeds.feedburner.com/etbsnl
HTTP Error (Code) and Message: (404) Feed not found error: FeedBurner cannot locate this feed URI.
