### ISSUE TITLE
Looking for new logo

### ISSUE THREAD

**Issue by Etuldan** [Etuldan/spaRSS#4]
At the moment, spaRSS use Flym images (with minor changes, as I don't have much time to change them and I have absolutely no artistic talent)

I'm looking for one logo (source SVG format required) that should be free (free to use, free to distribute, free to modify, ...). The artist will be mentioned on the credits list of spaRSS.
I can pay (if it's reasonable) for the job if the final product satisfy the above conditions.

**Comment by arunvikraman** [comment]
What message/feeling do you want your logo to convey?
any specific imagery in your mind for the logo?
any color preferences? any colors that you do not wish to use?
What adjectives should best describe your logo?
logos appeal to you and why?

**Comment by Etuldan** [comment]
A 'material design' logo is a must, but not an obligation.

A quick reference to feeds (like the 'original' logo for RSS https://en.wikipedia.org/wiki/RSS) can be cool, but not mandatory.
Also, it's not mandatory to add text in the logo (and I prefer to not add text, but you can if you want)
The typo, if you need to add text (case sensitive) is : spaRSS

**Comment by gversluis** [comment]
Would you like a RSS feed icon but in rainbow colours? :)
Or maybe a mirrored RSS icon at the top with a reflecting upsidedown RSS icon (which together forms an S from SpaRSS) ?
Can also do something with the feed as in http://media.catmoji.com/post/v0pe/feed-me-simons-cat.jpg ...
Give a direction and I'll see what I can do

**Comment by arunvikraman** [comment]
how do you like this http://imgur.com/Mg8w5BH

**Comment by arunvikraman** [comment]
![sparss](https://cloud.githubusercontent.com/assets/12801410/9584084/aa9fae9e-502c-11e5-88c3-ccecd6e5a92c.jpg)

**Comment by arunvikraman** [comment]
![spa2](https://cloud.githubusercontent.com/assets/12801410/9584203/8320d2de-502d-11e5-9221-d7caf79171f1.jpg)

**Comment by wp9015362** [comment]
@arunvikraman :

I am just a user of spaRSS, not it's developer, @Etuldan is (I think it's a little sad, that he hasn't commented on your proposals yet :stuck_out_tongue_closed_eyes: ), but:

I think from all the four logos that you have shown, the [second round one](https://cloud.githubusercontent.com/assets/12801410/9584203/8320d2de-502d-11e5-9221-d7caf79171f1.jpg) looks the best.

But:

Actually I do not really like any of those logos.

I think the new logo should not have the name "sparRSS" (or parts of it) in it.

I think it should rather show some variation of the feed icon in it, see:

https://en.wikipedia.org/wiki/Feed_icon

The original Sparse RSS also did that for it's logo, see for example:

https://code.google.com/p/sparserss/

Basically I think it should be a material design version of the [feed icon/symbol](https://en.wikipedia.org/wiki/Feed_icon).

But I think the symbol does not necessarily have to be exactly the same, it could also be some kind of variation of it, as long as it is still resembles the feed symbol in some way, so that the spaRSS logo makes it easy to recognize spaRSS as a feed aggregator app.

Also, the background of the logo does not necessarily need to be orange IMHO. It could also have another color IMHO.

But it should use colors from the Google Material Design Color Palette, see:

https://www.google.com/design/spec/style/color.html#color-color-palette

And it should adhere to the Google Material Design Product Icon Guidelines, see:

https://www.google.com/design/spec/style/icons.html#icons-product-icons

Any chance you could do something like that?

Regards

**Comment by Etuldan** [comment]
Sorry for the late response :/
Concerning logo, ( @arunvikraman ), it look nice, however, I would like to have some color ( that will probably redefined (see #78 ) and the "feed icon" in it.

@wp9015362 : "I think the new logo should not have the name "sparRSS" (nor parts of it) in it." => I think it's 'important' to have a dedicated logo, and not a simple 'feed icon' with only some swap colors or things like this. For example, if someone have 2 (or more) RSS app, he should be able to choose the correct one quickly.

**Comment by wp9015362** [comment]
> @Etuldan wrote:
> 
> I think it's 'important' to have a dedicated logo, and not a simple 'feed icon' with only some swap colors or things like this. For example, if someone have 2 (or more) RSS app, he should be able to choose the correct one quickly.

Yeah, I see.

But previously you wrote:

> @Etuldan wrote in https://github.com/Etuldan/spaRSS/issues/4#issuecomment-116628882:
> 
> Also, it's not mandatory to add text in the logo (and I prefer to not add text, but you can if you want)

:wink:

I think a unique logo with a unique icon/symbol in it would be nice. But I think the icon/symbol itself should not be made out of text like @arunvikraman did. It should rather be a proper symbol.

IMHO

Regards

**Comment by Etuldan** [comment]
Yep, but by text, I was talking about 'plain text'. My bad.
The 'demo' logo made by @arunvikraman is enough stylized to remove this impression of a text.
The logo could be the 'symbol' of spaRSS as I think many people will not notice that the logo is made of 3 letter S P and A.

And I prefer the square one (instead of the circle one), for the first comment (so without the heavy black color)

**Comment by arunvikraman** [comment]
![sparss](https://cloud.githubusercontent.com/assets/12801410/10118489/2a2ac77e-6497-11e5-805b-76c2b6eb184a.png)
i guess its pretty much a "symbol" now... its S.P.A. in a very abstract form. (atleast to me its still S.P.A.). with material colors and shadows..

**Comment by wp9015362** [comment]
@arunvikraman :

It does not have one of the keyline shapes from the Google Material Design Product Icons Guidelines (square, circle, vertical rectangle, horizontal rectangle), see:

https://www.google.com/design/spec/style/icons.html#icons-product-icons

Can you put it into a square or circle and make it cast some shadow like the feed icon does in the logo from @halcyonest from https://github.com/Etuldan/spaRSS/issues/86?

Regards

**Comment by Etuldan** [comment]
I think I'll use the @halcyonest one (from #86, the 3rd one).
So thanks @arunvikraman and @halcyonest for the work :)

**Comment by Etuldan** [comment]
Oops , forgot to add a mention about you, @darrenaronofsky (ex @arunvikraman ) and @halcyonest .
What name/nickname should I add in the about page ?

**Comment by darrenaronofsky** [comment]
never-mind... you can go with @halcyonest only. I was just hoping to find a fix in exchange (for issue #91) which sadly never materialized

**Comment by Etuldan** [comment]
@darrenaronofsky I'm sorry, but I don't have a full time to improve spaRSS, only some evenings and WeekEnd. I try my best, organizing bugs/FR by date and urgency and fix them all, one by one.

But, I insist, the logo was made by you and @halcyonest , so you can be in the "about page" ;) (no matter if you still use spaRSS or not, no matter if I do something else wrong) 
You help me a LOT by co-creating this logo, improving spaRSS visibility, making it unique.
