### ISSUE TITLE
Please add an option to always and immediately retrieve the full text

### ISSUE THREAD

**Issue by wp9015362** [Etuldan/spaRSS#45]
@Etuldan :

Thank you very much for forking Flym and continuing it's development! Much appreciated.

I've got a feature request:

Currently you always have to tap on "Retrieve the full text" for every single feed entry.

This can be quite annoying.

Could you please add an option to always and immediately retrieve the full text?

It would be much appreciated.

Regards

**Comment by ildar** [comment]
Disagree

-- 
Ildar Mulyukov,
child of God

email: ildar.mulyukov@gmail.com
GoogleTalk: ildar.mulyukov@gmail.com
blog: http://johan-notes.blogspot.com/

**Comment by wp9015362** [comment]
> @ildar wrote:
> 
> Disagree

I said "option"... What exactly is it that you need to disagree about an option?

**Comment by ildar** [comment]
FredJul decided it is important to avoid having too many options that
aren't important and polluting the UI.
I tend to think it is the good point

**Comment by wp9015362** [comment]
> @ildar wrote:
> 
> FredJul decided it is important to avoid having too many options that aren't important and polluting the UI.

As far as I can tell @FredJul is not the developer of spaRSS. @Etuldan is.

And to me this option would be very important as I am extremely annoyed having always to press the "Retrieve the full text" button before being able to read the entire feed entry.

What's even worse is, if you are in some area where there is no connectivity and then you can't retrieve the rest of the text.

This is highly annoying.

If there would be an option to always and immediately retrieve the full text, something like that would be less likely to happen, since the full text would already have been retrieved while there was still a connection available.

So, please don't says this isn't important. 

If you think this option is not important, then you probably think the "Preload images" option, which is already available, is also not important?

There's already a "Preload images" option, so an option to always and immediately retrieve the full text certainly wouldn't hurt.

**Comment by Etuldan** [comment]
@wp9015362 : FredJul is the developer of Flym. I forked Flym to create spaRSS, as FredJul didn't have enough time. Ildar was the "community manager" of Flym, and now continue with spaRSS (which is great :) )

Concerning options, yes, it could be great, but we have to take care about the multiplicity of them, avoiding to have a option page with thousand of options ;)

There is a option in the feed entry to enable "Retreive full text" for all the item of this feed.
Maybe you can't see it because of https://github.com/Etuldan/spaRSS/issues/29 ?

**Comment by wp9015362** [comment]
> @Etuldan wrote:
> 
> There is a option in the feed entry to enable "Retreive full text" for all the item of this feed.
Maybe you can't see it because of #29 ?

Ups, yes, I can see it on my device (5.2" @ 1080x1920), but I did not know that this option was there :open_mouth: .

That's also because when you go to edit feed, the keyboard hovers over those options, essentially hiding them.

Thank you very much for making me aware of this option.

Anyway, I still think there should be a global option for this.

I personally don't like that it has to be configured for each and every feed and I can't really imagine why exactly anyone would want to enable it for some feeds only.

And I also think this option is way too hidden.

But at least there is an option for it, good to know, thanks again.

**Comment by wp9015362** [comment]
PS:

The edit feed settings also have a setting for "Time that the entries will be kept" per feed.

But there is also a global setting for this.

So, if there can be a global setting for this as well as a per feed setting, then the same can be done for "Retrieve the full text".

IMHO

**Comment by ildar** [comment]
> I can't really imagine why exactly anyone would want to enable it for
some feeds only.
Full text isn't really a good thing and should be avoided as much as
possible, because:
1. It takes too much space: for an entry besides the space the entry
occupies as a part of its feed, the HTML text is bigger so the total space
per an entry is at least twice as big bug practically a few times bigger
(3-6 times maybe). Don't forget the full text page may theoretically
contain adv. content etc.
2. proportionally the downloading time and traffic is at least 2+ times
longer.

Also I'm not sure how often you do add new feeds. IMHO it's good just to a)
add a feed, b) do the 1st fetch (it is possible to update just one feed),
c) check if the Full text is required, d) check the checkbox if (c) is
positive.

**Comment by wp9015362** [comment]
> @ildar wrote:
> 
> 1. It takes too much space: for an entry besides the space the entry occupies as a part of its feed, the HTML text is bigger so the total space per an entry is at least twice as big bug practically a few times bigger (3-6 times maybe). Don't forget the full text page may theoretically contain adv. content etc.

What do you mean with "big"?

I really don't get what you mean.

> @ildar wrote:
> 
> c) check if the Full text is required

What?

Of course the full text is required if I want to read it.

Somehow I have a feeling that we both talk about different things.

When I don't tap on "Retrieve the full text", then I usually can't read the full news article, only the first part of it.

I need to tap on "Retrieve the full text" to be able to read the rest of the news article.

**Comment by ildar** [comment]
Feeds may be very different. They may bear very different types of
contents. Many of them don't need "Full text".
Anyway, what do you really want? Autofetching Full text? It is possible on
per-feed basis.
Global option? Hmm.
BTW you didn't answer how many feeds you add every day?

**Comment by wp9015362** [comment]
> @ildar wrote:
> 
> Many of them don't need "Full text".

As far as I can tell, all the feeds that I am using need "Retrieve the full text".

Let's take the Phoronix RSS feed for example:

http://www.phoronix.com/rss.php

When I don't tap on (or activate) "Retrieve the full text", then spaRSS will only show the first few lines/the first paragraph of the article.

It's merely a preview.

I have to tap on (or activate) "Retrieve the full text" to be able to see the rest of the article.

Maybe I'm doing something wrong?

If yes, feel free to explain :wink:.

> @ildar wrote:
> 
> BTW you didn't answer how many feeds you add every day?

Usually not daily. Maybe every several months or so.

I guess you are trying to argue that if I am not adding a lot of feeds over a short period of time, then I shouldn't complain about having to enable an option per feed, since it's not much of an effort if I haven't have to do it that often anyway.

But your argument immediately becomes moot when you think about what happens if a user imports an OMPL file containing a lot of feeds.

Then he suddenly has to enable that option for several feeds at once, which can be very time consuming and very annoying, even if you are doing it just once per year for example.

Regards

**Comment by ildar** [comment]
Again, as I wrote:
> Feeds may be very different.
I believe that 100% (or maybe more) of YOUR feeds need Full text. But
that's not the same for many-many others.
And for the importing use-case, I believe that if a user has a time to read
(number of feeds * some avg number of posts) then he definitely has a time
to tap (number of feeds or less) times checkboxes for Full text.
Anyway the discussion is less and less sensible and more and more noisy.
I'm to finish here.
After all the developer has to decide.

**Comment by nico202** [comment]
@wp9015362 I'm in your same situation (and use phoronix too), but @ildar I'd like to have an "auto full text" because I'd like to read it offline, so tapping "full text" is not an option, not because of the lack of time, but for the lack of internet access. As it is now, is quite useless. Also, if we have the "auto download on wifi" I don't think that this is a Mb/time to download problems. We are talking of text. Text. 2kb vs 10 kb is.. isn't it the same?
If the matter is "polluting the ui", we can have a "advanced options", or a config file for advanced users, or a hidden option that you can activate jumping twice on your left leg

**Comment by Etuldan** [comment]
@nico202 : There is already an "auto full text" option, as said before, in the feed option (Advanced Tab)

**Comment by nico202** [comment]
ooops sorry, shame on me. Thanks :)

**Comment by Etuldan** [comment]
Option moved back to the 'basic' tab when adding a feed, for a better use.
